mach-snapdragon: fix OP-TEE SPL link failure
Use CONFIG_IS_ENABLED(OPTEE) instead of IS_ENABLED(CONFIG_OPTEE)
to avoid calling OP-TEE APIs in SPL builds where the driver is
not available, fixing the SPL link error.

Fixes: undefined reference to `is_optee_smc_api' in spl/u-boot-spl

Signed-off-by: Aswin Murugan <aswin.murugan@oss.qualcomm.com>